apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "collectd.infra.watch/v1alpha1",
          "kind": "Collectd",
          "metadata": {
            "name": "collectd"
          },
          "spec": {}
        }
      ]
    capabilities: Basic Install
  name: collectd-operator.v0.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Instance of collectd
      displayName: Collectd
      kind: Collectd
      name: collectds.collectd.infra.watch
      resources:
      - kind: Pod
        name: ""
        version: v1
      - kind: Deployments
        name: ""
        version: v1
      - kind: ReplicaSets
        name: ""
        version: v1
      - kind: DaemonSets
        name: ""
        version: v1
      - kind: Services
        name: ""
        version: v1
      - kind: ConfigMaps
        name: ""
        version: v1
      - kind: Collectds
        name: ""
        version: v1alpha1
      specDescriptors:
      - description: Number of Collectds to deploy
        displayName: Size
        path: size
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      statusDescriptors:
      - description: Conditions provided by deployment
        displayName: Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      version: v1alpha1
  description: Operator for launching collectd on k8s
  displayName: Collectd Operator
  install:
    spec:
      deployments:
      - name: collectd-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: collectd-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: collectd-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: quay.io/leifmadsen/collectd-operator:latest
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: collectd-operator
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/leifmadsen/collectd-operator:latest
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: collectd-operator
              volumes:
              - emptyDir: {}
                name: runner
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - serviceaccounts
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - collectd-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - collectd.infra.watch
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: collectd-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - monitoring
  - collectd
  maintainers:
  - email: lmadsen+collectd-operator@redhat.com
    name: Leif Madsen
  maturity: alpha
  provider:
    name: InfraWatch
  replaces: collectd-operator.v0.0.1
  version: 0.0.2
