apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: collectds.collectd.infra.watch
spec:
  group: collectd.infra.watch
  names:
    kind: Collectd
    listKind: CollectdList
    plural: collectds
    singular: collectd
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: "APIVersion"
          type: string
        kind:
          description: "Kind"
          type: string
        spec:
          description: "CollectdSpec"
          properties:
            collectdHost:
              description: "QPID Dispatch Router host for amqp1 plugin connection"
              type: string
            collectdPort:
              description: "QPID Dispatch Router port for amqp1 plugin connection"
              type: integer
            collectdInterval:
              description: "Interval to collect metrics (in seconds)"
              type: integer
            collectdImage:
              description: "Container image path for collectd"
              type: string
            collectImageTag:
              description: "Container image tag for collectd"
              type: string
        status:
          description: Status results of Collectd
          properties:
            conditions:
              description: The resulting conditions when Collectd is instantiated
              items:
                properties:
                  status:
                    type: string
                  type:
                    type: string
                  reason:
                    type: string
                  lastTransitionTime:
                    type: string
                type: object
              type: array
          type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
