apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: collectds.collectd.infra.watch
spec:
  group: collectd.infra.watch
  names:
    kind: Collectd
    listKind: CollectdList
    plural: collectds
    singular: collectd
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
